apiVersion: v1
kind: Service
metadata:
  name: {{ include "grpc-go.fullname" . }}-service
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "grpc-go.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: tcp
  selector:
    {{- include "grpc-go.selectorLabels" . | nindent 4 }}
    type: server
