apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "grpc-go.serviceAccountName" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "grpc-go.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
