apiVersion: v1
kind: Namespace
metadata:
  name: grpc-go
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: grpc-go-sa
  namespace: grpc-go
---
apiVersion: v1
kind: Service
metadata:
  name: grpc-go-server-service
  namespace: grpc-go
spec:
  selector:
    app: grpc-go-server-app
  ports:
    - protocol: TCP
      port: 50051
      targetPort: 50051
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grpc-go-server-deployment
  namespace: grpc-go
  labels:
    app: grpc-go-server-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grpc-go-server-app
  template:
    metadata:
      labels:
        app: grpc-go-server-app
    spec:
      containers:
        - name: grpc-go-server
          image: raymondsquared/grpc-helloworld-server:0.0.2-20250630a
          ports:
            - containerPort: 50051
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 250m
              memory: 256Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grpc-go-client-deployment
  namespace: grpc-go
  labels:
    app: grpc-go-client-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grpc-go-client-app
  template:
    metadata:
      labels:
        app: grpc-go-client-app
    spec:
      containers:
        - name: grpc-go-client
          image: raymondsquared/grpc-helloworld-client:0.0.2-20250630a
          ports:
            - containerPort: 50051
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 250m
              memory: 256Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grpc-go-full-deployment
  namespace: grpc-go
  labels:
    app: grpc-go-full-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grpc-go-full-app
  template:
    metadata:
      labels:
        app: grpc-go-full-app
    spec:
      serviceAccountName: grpc-go-sa
      securityContext:
        fsGroup: 1000
        runAsGroup: 1000
        runAsUser: 1000
        supplementalGroups:
          - 1000
      containers:
        - name: grpc-go-full
          image: raymondsquared/grpc-helloworld-full:0.0.2-20250630a
          ports:
            - containerPort: 50051
              protocol: TCP
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 250m
              memory: 256Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            privileged: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true
