// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: movie_messages.proto

package movie

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetMovieInput struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	MinimumRatingsScore float32                `protobuf:"fixed32,1,opt,name=minimum_ratings_score,json=minimumRatingsScore,proto3" json:"minimum_ratings_score,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *GetMovieInput) Reset() {
	*x = GetMovieInput{}
	mi := &file_movie_messages_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMovieInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMovieInput) ProtoMessage() {}

func (x *GetMovieInput) ProtoReflect() protoreflect.Message {
	mi := &file_movie_messages_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMovieInput.ProtoReflect.Descriptor instead.
func (*GetMovieInput) Descriptor() ([]byte, []int) {
	return file_movie_messages_proto_rawDescGZIP(), []int{0}
}

func (x *GetMovieInput) GetMinimumRatingsScore() float32 {
	if x != nil {
		return x.MinimumRatingsScore
	}
	return 0
}

type GetMovieOutput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Movie         []*Movie               `protobuf:"bytes,1,rep,name=movie,proto3" json:"movie,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMovieOutput) Reset() {
	*x = GetMovieOutput{}
	mi := &file_movie_messages_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMovieOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMovieOutput) ProtoMessage() {}

func (x *GetMovieOutput) ProtoReflect() protoreflect.Message {
	mi := &file_movie_messages_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMovieOutput.ProtoReflect.Descriptor instead.
func (*GetMovieOutput) Descriptor() ([]byte, []int) {
	return file_movie_messages_proto_rawDescGZIP(), []int{1}
}

func (x *GetMovieOutput) GetMovie() []*Movie {
	if x != nil {
		return x.Movie
	}
	return nil
}

type Movie struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MovieId       string                 `protobuf:"bytes,1,opt,name=movie_id,json=movieId,proto3" json:"movie_id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	ReleaseDate   string                 `protobuf:"bytes,3,opt,name=release_date,json=releaseDate,proto3" json:"release_date,omitempty"`
	Genre         []string               `protobuf:"bytes,4,rep,name=genre,proto3" json:"genre,omitempty"`
	Director      *Director              `protobuf:"bytes,5,opt,name=director,proto3" json:"director,omitempty"`
	Producer      []*Producer            `protobuf:"bytes,6,rep,name=producer,proto3" json:"producer,omitempty"`
	Cast          []*CastMember          `protobuf:"bytes,7,rep,name=cast,proto3" json:"cast,omitempty"`
	Crew          []*CrewMember          `protobuf:"bytes,8,rep,name=crew,proto3" json:"crew,omitempty"`
	PlotSummary   string                 `protobuf:"bytes,9,opt,name=plot_summary,json=plotSummary,proto3" json:"plot_summary,omitempty"`
	RatingsScore  float32                `protobuf:"fixed32,10,opt,name=ratings_score,json=ratingsScore,proto3" json:"ratings_score,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Movie) Reset() {
	*x = Movie{}
	mi := &file_movie_messages_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Movie) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Movie) ProtoMessage() {}

func (x *Movie) ProtoReflect() protoreflect.Message {
	mi := &file_movie_messages_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Movie.ProtoReflect.Descriptor instead.
func (*Movie) Descriptor() ([]byte, []int) {
	return file_movie_messages_proto_rawDescGZIP(), []int{2}
}

func (x *Movie) GetMovieId() string {
	if x != nil {
		return x.MovieId
	}
	return ""
}

func (x *Movie) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Movie) GetReleaseDate() string {
	if x != nil {
		return x.ReleaseDate
	}
	return ""
}

func (x *Movie) GetGenre() []string {
	if x != nil {
		return x.Genre
	}
	return nil
}

func (x *Movie) GetDirector() *Director {
	if x != nil {
		return x.Director
	}
	return nil
}

func (x *Movie) GetProducer() []*Producer {
	if x != nil {
		return x.Producer
	}
	return nil
}

func (x *Movie) GetCast() []*CastMember {
	if x != nil {
		return x.Cast
	}
	return nil
}

func (x *Movie) GetCrew() []*CrewMember {
	if x != nil {
		return x.Crew
	}
	return nil
}

func (x *Movie) GetPlotSummary() string {
	if x != nil {
		return x.PlotSummary
	}
	return ""
}

func (x *Movie) GetRatingsScore() float32 {
	if x != nil {
		return x.RatingsScore
	}
	return 0
}

type Director struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Director) Reset() {
	*x = Director{}
	mi := &file_movie_messages_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Director) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Director) ProtoMessage() {}

func (x *Director) ProtoReflect() protoreflect.Message {
	mi := &file_movie_messages_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Director.ProtoReflect.Descriptor instead.
func (*Director) Descriptor() ([]byte, []int) {
	return file_movie_messages_proto_rawDescGZIP(), []int{3}
}

func (x *Director) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type Producer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Producer) Reset() {
	*x = Producer{}
	mi := &file_movie_messages_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Producer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Producer) ProtoMessage() {}

func (x *Producer) ProtoReflect() protoreflect.Message {
	mi := &file_movie_messages_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Producer.ProtoReflect.Descriptor instead.
func (*Producer) Descriptor() ([]byte, []int) {
	return file_movie_messages_proto_rawDescGZIP(), []int{4}
}

func (x *Producer) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type CastMember struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ActorName     string                 `protobuf:"bytes,1,opt,name=actor_name,json=actorName,proto3" json:"actor_name,omitempty"`
	CharacterName string                 `protobuf:"bytes,2,opt,name=character_name,json=characterName,proto3" json:"character_name,omitempty"`
	Role          string                 `protobuf:"bytes,3,opt,name=role,proto3" json:"role,omitempty"`
	Biography     string                 `protobuf:"bytes,4,opt,name=biography,proto3" json:"biography,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CastMember) Reset() {
	*x = CastMember{}
	mi := &file_movie_messages_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CastMember) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CastMember) ProtoMessage() {}

func (x *CastMember) ProtoReflect() protoreflect.Message {
	mi := &file_movie_messages_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CastMember.ProtoReflect.Descriptor instead.
func (*CastMember) Descriptor() ([]byte, []int) {
	return file_movie_messages_proto_rawDescGZIP(), []int{5}
}

func (x *CastMember) GetActorName() string {
	if x != nil {
		return x.ActorName
	}
	return ""
}

func (x *CastMember) GetCharacterName() string {
	if x != nil {
		return x.CharacterName
	}
	return ""
}

func (x *CastMember) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *CastMember) GetBiography() string {
	if x != nil {
		return x.Biography
	}
	return ""
}

type CrewMember struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Role          string                 `protobuf:"bytes,2,opt,name=role,proto3" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CrewMember) Reset() {
	*x = CrewMember{}
	mi := &file_movie_messages_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CrewMember) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CrewMember) ProtoMessage() {}

func (x *CrewMember) ProtoReflect() protoreflect.Message {
	mi := &file_movie_messages_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CrewMember.ProtoReflect.Descriptor instead.
func (*CrewMember) Descriptor() ([]byte, []int) {
	return file_movie_messages_proto_rawDescGZIP(), []int{6}
}

func (x *CrewMember) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CrewMember) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

type MovieProtoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProtoContent  string                 `protobuf:"bytes,1,opt,name=proto_content,json=protoContent,proto3" json:"proto_content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MovieProtoResponse) Reset() {
	*x = MovieProtoResponse{}
	mi := &file_movie_messages_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MovieProtoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MovieProtoResponse) ProtoMessage() {}

func (x *MovieProtoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_movie_messages_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MovieProtoResponse.ProtoReflect.Descriptor instead.
func (*MovieProtoResponse) Descriptor() ([]byte, []int) {
	return file_movie_messages_proto_rawDescGZIP(), []int{7}
}

func (x *MovieProtoResponse) GetProtoContent() string {
	if x != nil {
		return x.ProtoContent
	}
	return ""
}

var File_movie_messages_proto protoreflect.FileDescriptor

const file_movie_messages_proto_rawDesc = "" +
	"\n" +
	"\x14movie_messages.proto\x12\x05movie\"C\n" +
	"\rGetMovieInput\x122\n" +
	"\x15minimum_ratings_score\x18\x01 \x01(\x02R\x13minimumRatingsScore\"4\n" +
	"\x0eGetMovieOutput\x12\"\n" +
	"\x05movie\x18\x01 \x03(\v2\f.movie.MovieR\x05movie\"\xe1\x02\n" +
	"\x05Movie\x12\x19\n" +
	"\bmovie_id\x18\x01 \x01(\tR\amovieId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12!\n" +
	"\frelease_date\x18\x03 \x01(\tR\vreleaseDate\x12\x14\n" +
	"\x05genre\x18\x04 \x03(\tR\x05genre\x12+\n" +
	"\bdirector\x18\x05 \x01(\v2\x0f.movie.DirectorR\bdirector\x12+\n" +
	"\bproducer\x18\x06 \x03(\v2\x0f.movie.ProducerR\bproducer\x12%\n" +
	"\x04cast\x18\a \x03(\v2\x11.movie.CastMemberR\x04cast\x12%\n" +
	"\x04crew\x18\b \x03(\v2\x11.movie.CrewMemberR\x04crew\x12!\n" +
	"\fplot_summary\x18\t \x01(\tR\vplotSummary\x12#\n" +
	"\rratings_score\x18\n" +
	" \x01(\x02R\fratingsScore\"\x1e\n" +
	"\bDirector\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"\x1e\n" +
	"\bProducer\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"\x84\x01\n" +
	"\n" +
	"CastMember\x12\x1d\n" +
	"\n" +
	"actor_name\x18\x01 \x01(\tR\tactorName\x12%\n" +
	"\x0echaracter_name\x18\x02 \x01(\tR\rcharacterName\x12\x12\n" +
	"\x04role\x18\x03 \x01(\tR\x04role\x12\x1c\n" +
	"\tbiography\x18\x04 \x01(\tR\tbiography\"4\n" +
	"\n" +
	"CrewMember\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04role\x18\x02 \x01(\tR\x04role\"9\n" +
	"\x12MovieProtoResponse\x12#\n" +
	"\rproto_content\x18\x01 \x01(\tR\fprotoContentB\x1dZ\x1bcase-studies/grpc/cmd/movieb\x06proto3"

var (
	file_movie_messages_proto_rawDescOnce sync.Once
	file_movie_messages_proto_rawDescData []byte
)

func file_movie_messages_proto_rawDescGZIP() []byte {
	file_movie_messages_proto_rawDescOnce.Do(func() {
		file_movie_messages_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_movie_messages_proto_rawDesc), len(file_movie_messages_proto_rawDesc)))
	})
	return file_movie_messages_proto_rawDescData
}

var file_movie_messages_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_movie_messages_proto_goTypes = []any{
	(*GetMovieInput)(nil),      // 0: movie.GetMovieInput
	(*GetMovieOutput)(nil),     // 1: movie.GetMovieOutput
	(*Movie)(nil),              // 2: movie.Movie
	(*Director)(nil),           // 3: movie.Director
	(*Producer)(nil),           // 4: movie.Producer
	(*CastMember)(nil),         // 5: movie.CastMember
	(*CrewMember)(nil),         // 6: movie.CrewMember
	(*MovieProtoResponse)(nil), // 7: movie.MovieProtoResponse
}
var file_movie_messages_proto_depIdxs = []int32{
	2, // 0: movie.GetMovieOutput.movie:type_name -> movie.Movie
	3, // 1: movie.Movie.director:type_name -> movie.Director
	4, // 2: movie.Movie.producer:type_name -> movie.Producer
	5, // 3: movie.Movie.cast:type_name -> movie.CastMember
	6, // 4: movie.Movie.crew:type_name -> movie.CrewMember
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_movie_messages_proto_init() }
func file_movie_messages_proto_init() {
	if File_movie_messages_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_movie_messages_proto_rawDesc), len(file_movie_messages_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_movie_messages_proto_goTypes,
		DependencyIndexes: file_movie_messages_proto_depIdxs,
		MessageInfos:      file_movie_messages_proto_msgTypes,
	}.Build()
	File_movie_messages_proto = out.File
	file_movie_messages_proto_goTypes = nil
	file_movie_messages_proto_depIdxs = nil
}
