// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: movie_services.proto

package movie

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_movie_services_proto protoreflect.FileDescriptor

const file_movie_services_proto_rawDesc = "" +
	"\n" +
	"\x14movie_services.proto\x12\x05movie\x1a\x14movie_messages.proto\x1a\x1bgoogle/protobuf/empty.proto2L\n" +
	"\x06Getter\x12B\n" +
	"\x11GetMovieByRatings\x12\x14.movie.GetMovieInput\x1a\x15.movie.GetMovieOutput\"\x002Z\n" +
	"\x11MovieProtoService\x12E\n" +
	"\x0eGetMoviesProto\x12\x16.google.protobuf.Empty\x1a\x19.movie.MovieProtoResponse\"\x00B\x1dZ\x1bcase-studies/grpc/cmd/movieb\x06proto3"

var file_movie_services_proto_goTypes = []any{
	(*GetMovieInput)(nil),      // 0: movie.GetMovieInput
	(*emptypb.Empty)(nil),      // 1: google.protobuf.Empty
	(*GetMovieOutput)(nil),     // 2: movie.GetMovieOutput
	(*MovieProtoResponse)(nil), // 3: movie.MovieProtoResponse
}
var file_movie_services_proto_depIdxs = []int32{
	0, // 0: movie.Getter.GetMovieByRatings:input_type -> movie.GetMovieInput
	1, // 1: movie.MovieProtoService.GetMoviesProto:input_type -> google.protobuf.Empty
	2, // 2: movie.Getter.GetMovieByRatings:output_type -> movie.GetMovieOutput
	3, // 3: movie.MovieProtoService.GetMoviesProto:output_type -> movie.MovieProtoResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_movie_services_proto_init() }
func file_movie_services_proto_init() {
	if File_movie_services_proto != nil {
		return
	}
	file_movie_messages_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_movie_services_proto_rawDesc), len(file_movie_services_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_movie_services_proto_goTypes,
		DependencyIndexes: file_movie_services_proto_depIdxs,
	}.Build()
	File_movie_services_proto = out.File
	file_movie_services_proto_goTypes = nil
	file_movie_services_proto_depIdxs = nil
}
