// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: movie_services.proto

package movie

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Getter_GetMovieByRatings_FullMethodName     = "/movie.Getter/GetMovieByRatings"
	Getter_GetMovieByRatingsChat_FullMethodName = "/movie.Getter/GetMovieByRatingsChat"
)

// GetterClient is the client API for Getter service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GetterClient interface {
	GetMovieByRatings(ctx context.Context, in *GetMovieInput, opts ...grpc.CallOption) (*GetMovieOutput, error)
	GetMovieByRatingsChat(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[GetMovieInput, GetMovieOutput], error)
}

type getterClient struct {
	cc grpc.ClientConnInterface
}

func NewGetterClient(cc grpc.ClientConnInterface) GetterClient {
	return &getterClient{cc}
}

func (c *getterClient) GetMovieByRatings(ctx context.Context, in *GetMovieInput, opts ...grpc.CallOption) (*GetMovieOutput, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetMovieOutput)
	err := c.cc.Invoke(ctx, Getter_GetMovieByRatings_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *getterClient) GetMovieByRatingsChat(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[GetMovieInput, GetMovieOutput], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Getter_ServiceDesc.Streams[0], Getter_GetMovieByRatingsChat_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[GetMovieInput, GetMovieOutput]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Getter_GetMovieByRatingsChatClient = grpc.BidiStreamingClient[GetMovieInput, GetMovieOutput]

// GetterServer is the server API for Getter service.
// All implementations must embed UnimplementedGetterServer
// for forward compatibility.
type GetterServer interface {
	GetMovieByRatings(context.Context, *GetMovieInput) (*GetMovieOutput, error)
	GetMovieByRatingsChat(grpc.BidiStreamingServer[GetMovieInput, GetMovieOutput]) error
	mustEmbedUnimplementedGetterServer()
}

// UnimplementedGetterServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGetterServer struct{}

func (UnimplementedGetterServer) GetMovieByRatings(context.Context, *GetMovieInput) (*GetMovieOutput, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMovieByRatings not implemented")
}
func (UnimplementedGetterServer) GetMovieByRatingsChat(grpc.BidiStreamingServer[GetMovieInput, GetMovieOutput]) error {
	return status.Errorf(codes.Unimplemented, "method GetMovieByRatingsChat not implemented")
}
func (UnimplementedGetterServer) mustEmbedUnimplementedGetterServer() {}
func (UnimplementedGetterServer) testEmbeddedByValue()                {}

// UnsafeGetterServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GetterServer will
// result in compilation errors.
type UnsafeGetterServer interface {
	mustEmbedUnimplementedGetterServer()
}

func RegisterGetterServer(s grpc.ServiceRegistrar, srv GetterServer) {
	// If the following call pancis, it indicates UnimplementedGetterServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Getter_ServiceDesc, srv)
}

func _Getter_GetMovieByRatings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMovieInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GetterServer).GetMovieByRatings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Getter_GetMovieByRatings_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GetterServer).GetMovieByRatings(ctx, req.(*GetMovieInput))
	}
	return interceptor(ctx, in, info, handler)
}

func _Getter_GetMovieByRatingsChat_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(GetterServer).GetMovieByRatingsChat(&grpc.GenericServerStream[GetMovieInput, GetMovieOutput]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Getter_GetMovieByRatingsChatServer = grpc.BidiStreamingServer[GetMovieInput, GetMovieOutput]

// Getter_ServiceDesc is the grpc.ServiceDesc for Getter service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Getter_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "movie.Getter",
	HandlerType: (*GetterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetMovieByRatings",
			Handler:    _Getter_GetMovieByRatings_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetMovieByRatingsChat",
			Handler:       _Getter_GetMovieByRatingsChat_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "movie_services.proto",
}
